message = require './message'
require '../../../vendor/assets/bower_components/fitvids/jquery.fitvids'
require '../../../vendor/assets/bower_components/list.js/dist/list.min'
require './jquery-fn'
require './best_in_place'
require './dropdown-menu'
require './category-filter'
require './pushy'
require './show-hide-pass'
require './signin_modal'
require './embed_youtube_iframe'
require './auto-textarea-height'
require './comments'
require './reduce-sidebar'
require './course-nav'
require './articles-sort'

console.log message
