message = require './message'
require '../../../vendor/assets/bower_components/fitvids/jquery.fitvids'
require '../../../vendor/assets/bower_components/list.js/dist/list.min'
require '../../../vendor/assets/bower_components/perfect-scrollbar/js/min/perfect-scrollbar.jquery.min'
require './jquery-fn'
require './best_in_place'
require './dropdown-menu'
require './category-filter'
require './pushy'
require './show-hide-pass'
require './signin_modal'
require './embed_youtube_iframe'
require './auto-textarea-height'
require './reduce-sidebar'
require './course-nav'
require './articles-sort'
require './flashes'
require './course-playlist'
require './perfecr-scrollbar'

require './comments'
require './reviews'

console.log message
